### ISSUE TITLE
Please support other databases

### ISSUE THREAD

**Issue by nob13** [squidnyan/docker-registry-ui#138]
H2 on file is not very stable on restarting docker images. It often reports "database in use".

It would be great if you could support other databases like postgres as they are easy to install with docker nowadays.

**Comment by atc-** [comment]
Is there a reason you're not parameterising using the Docker image's environment parameters for the registry configuration e.g. `-e REG1=http://someserver:5000/v1/` ? That means the registry config is stateless because it can be resetarted with the same params and doesn't require setup once started.

**Comment by nob13** [comment]
Ah. I am starting the registry-ui with the parameter. However it was still creating the database and so I was still exporting it to an external volume where this restart problems occured. I think if there is no further data, I can live with the H2 being on a temporary directory (or non exported).

**Comment by atc-** [comment]
Any reason you're exporting the external volume? If you're using the parameters then there's no need (as far as I can tell).

**Comment by nob13** [comment]
Oh, just out of habit, I thought there would be something more in the DB.

**Comment by atc-** [comment]
The only state kept in the in-memory database is the registry configuration, that can be changed at runtime. If you're using the parameters then keeping the volume around is superfluous.

If you agree, I'll close this issue.

**Comment by nob13** [comment]
I'm fine with closing.
Am 31.03.2015 09:38 schrieb "Alex Collins" <notifications@github.com>:

The only state kept in the in-memory database is the registry
configuration, that can be changed at runtime. If you're using the
parameters then keeping the volume around is superfluous.

If you agree, I'll close this issue.

—
Reply to this email directly or view it on GitHub
<https://github.com/atc-/docker-registry-ui/issues/138#issuecomment-87979491>
.
