### ISSUE TITLE
0.9.1 registry not working with ping failed

### ISSUE THREAD

**Issue by xiaods** [squidnyan/docker-registry-ui#140]
ubuntu@VM-24-164-ubuntu:~$ curl http://10.105.24.164:5000/v1/_ping
{}

does it make sense?

**Comment by xiaods** [comment]
with talk about this issue with registry repo owner, i think docker-registry-ui not correctly handle the {} with status 200.

**Comment by lioncui** [comment]
I have a similar issue, use curl command return 200 status.
[root@centos6 ~]# curl -i -X GET http://10.0.0.3:5100/v1/_ping
HTTP/1.1 200 OK
X-Docker-Registry-Version: 0.8.0
Date: Thu, 08 Oct 2015 11:54:58 GMT
Connection: keep-alive
Transfer-Encoding: chunked

-------------------
but registry-ui add registry faild, /v1/_ping error.

**Comment by ndhuynh** [comment]
I have the same  issues. 
More details here: 
- case 1:
#registry-ui 
docker run -d -p 8081:8080 --name registry-ui-01 --link registry:registry  -e REG1=https://ndhuynh:passwod@registry.mydomain.vn:5000/v2/  -v `pwd`/trustedCA/truststore:/trustsre -e 'JAVA_OPTS=-Djavax.net.ssl.trustStore=/truststore -Djavax.net.ssl.trustStorePassword=password' atcol/docker-registry-ui

# log of registry
 ERROR conf.BootStrap  - Couldn't parse valid registry URL from https://ndhuynh:password@registry.spsvietnam.vn:5000/v2/

- case 2: 
# in registry-ui
docker run -d -p 8081:8080 --name registry-ui-01 --link registry:registry  -v `pwd`/trustedCA/truststore:/trustsre -e 'JAVA_OPTS=-Djavax.net.ssl.trustStore=/truststore -Djavax.net.ssl.trustStorePassword=password' atcol/docker-registry-ui

Logs: 
2015-11-18 08:59:37,247 [http-bio-8080-exec-6] ERROR web.RepositoryService  - Failed to ping https://ndhuynh:abc123@registry.spsvietnam.vn:5000/v1/_ping: 404 : Not Found

**Comment by pengjian01** [comment]
Failed to ping https://dockerhub.lefile.cn:443/v1/_ping: 404 : Not Found
