### ISSUE TITLE
API V2 Support

### ISSUE THREAD

**Issue by vladkras** [squidnyan/docker-registry-ui#162]
My local registry runs API v2 and I saved its settings API version: v2
but it produces
`Oh no! This registry is unreachable!` error in UI

v2 isn't supported yet, is it?

**Comment by atcol** [comment]
Working on this now.

**Comment by soosap** [comment]
Hi and thanks for this project. I am looking to get this running w/ v2. Can you update us on the state of this issue? What is currently blocking this? Are we close to get this resolved or any information about the state of this would help :) Thank you very much.

**Comment by squidnyan** [comment]
We are close to getting this resolved. I'm trying to finish it today.

**Comment by squidnyan** [comment]
Now in master.
